# prometheus-values.yaml
crds:
  enabled: true
kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "250m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

grafana:
  enabled: true
  service:
    type: LoadBalancer
  adminPassword: ""
  persistence:
    enabled: true
    storageClassName: "longhorn"
    size: 10Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  grafana.ini:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
