authentik:
  secret_key: ""
  error_reporting:
    enabled: true
  postgresql:
    password: ""

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    pathType: Prefix
    hosts:
      - auth.batk.me
    tls:
      - hosts:
          - auth.batk.me
        secretName: authentik-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      acme.cert-manager.io/http01-edit-in-place: "true"  # Add this line
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

postgresql:
  enabled: true
  auth:
    password: ""

redis:
  enabled: true
