---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-secret-access
subjects:
  - kind: ServiceAccount
    name: tailscale-sa
    namespace: headscale
roleRef:
  kind: Role
  name: tailscale-secret-manager
  apiGroup: rbac.authorization.k8s.io
