---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale-auth"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
