---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        type: LoadBalancer
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      data:
        # Basic rate limiting
        rate-limit-rpm: "1200"
        rate-limit-connections: "20"

        # Custom nginx config for more granular control
        http-snippet: |
          # Define rate limit zones
          limit_req_zone $binary_remote_addr zone=login:10m rate=10r/m;
          limit_req_zone $binary_remote_addr zone=git:10m rate=100r/m;
          limit_req_zone $binary_remote_addr zone=global:10m rate=300r/m;

        server-snippet: |
          # Global rate limiting
          limit_req zone=global burst=50 nodelay;

          # Strict limits for authentication
          location ~* /user/(login|sign_up) {
            limit_req zone=login burst=10 nodelay;
            limit_req_status 429;
          }

          # Git operations rate limiting
          location ~* \.(git|hg)/ {
            limit_req zone=git burst=20 nodelay;
            limit_req_status 429;
          }
